CPPFLAGS=-Werror -Wall -Wextra -Wunreachable-code -Wuninitialized -pedantic-errors -Wno-error=unused-variable -Wshadow -Wnon-virtual-dtor
MAKEFLAGS="-j 12"

program: program.cpp
	g++ $(CPPFLAGS) -o program program.cpp
