CPPFLAGS=-Werror -Wall -Wextra -Wconversion -Wunreachable-code -Wuninitialized -pedantic-errors -Wno-error=unused-variable -Wshadow -Wnon-virtual-dtor
MAKEFLAGS="-j 12"

drill: drill.cpp
	g++ $(CPPFLAGS) -o drill drill.cpp
